services:
  db:
    image: postgres:17.4
    restart: always
    volumes:
      - ./data/db/:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      retries: 5
    networks:
      - grex-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/ai_assistant/model/grex-distilbert:/app/ai_assistant/model/grex-distilbert:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - grex-net
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "15433:80"
    env_file:
      - .env
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - grex-net


networks:
  grex-net:
    driver: bridge
